config/routes.rb
Rails.application.routes.draw do
  root to: 'gossips#index'
resources :gossips
resources :cities
resources :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  validates :name,presence: true
  validates :zip_code,presence: true,uniqueness: true,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content,presence: true
  validates :user_id,presence: true
  validates :gossip_id,presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes
  validates :title,presence: true,length: { in: 1..25 }
  validates :content,presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
 belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :likes
  validates :email,presence: true,uniqueness: true,format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Mauvais format" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossip = Gossip.all
  end

  def show
    @find = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: 4) # avec xxx qui sont les données obtenues à partir du formulaire

  if @gossip.save # essaie de sauvegarder en base @gossip
    redirect_to gossips_path
  else
    render new_gossip_path
  end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
    @users =  User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h1>Cities#show</h1>
<p>Find me in app/views/cities/show.html.erb</p>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<p>Find me in app/views/gossips/edit.html.erb</p>

app/views/gossips/index.html.erb
<div class="card">
  	  <div class="card-body" style="background-color: #1098E5;">
		  <h1 style="text-align: center;">BIENVENUE!</h1>
			<h2 style="text-align: center;"> Ici c'est notre super site de potins, il est chouette, non ?</h2>
	    </div>
    </div>



  

    <div class="card">
 	    <div class="card-body">
  	    <h3> Voici la listes des Gossips: </h3>
 	    </div>
    </div>

   <%	@gossip.each_with_index do |gossip, index|%>
   <div class="card text-center">
   <div class="card-header" style="background-color: #4E5554;">
    Potin N° <%=index + 1%>
   </div>
   <div class="card-body" style="background-color: #2B2F2F;">
    <h3 class="card-title"><%= gossip.user.first_name %></h3>
    <h2 class="card-text"><%= gossip.title %></h2>
    <p> <%= link_to "Afficher le potin", gossip_path(index + 1)%> </p>
   </div>
   <div class="card-footer text-muted" style="background-color: #4E5554;">
    crée le <%= gossip.created_at%>
   </div>
   </div>
   <h3> _ </h3>
   <% end %>

app/views/gossips/new.html.erb
<form action= <%= gossips_path %> method="POST">
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Title <input type="text" name="title"><br>
      Content <input type="text" name="content"><br>
      <input type="submit" value="Valider">
</form>

app/views/gossips/show.html.erb
<head>
  
</head>
<body>
  <div class="card text-center">
    <div class="card-header">
      <%= @find.user.first_name %> <%= @find.user.last_name %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @find.title %></h5>
      <p class="card-text"><%= @find.content %></p>
      <%= link_to "A  propos de l'auteur", user_path(@find.user.id)%>
    </div>
    <div class="card-footer text-muted">
      <%= @find.created_at %>
    </div>
  </div>
</body>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>GossipProjectViews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/team">Team</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="badge badge-secondary" href="/contact">Contact</a>
      </li>
      <li class="nav-item dropdown">
        <a class="badge badge-primary" href="/create">Create</a>
        <%= link_to "creer un nouveau potin", new_gossip_path%>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

   <div class="p-3 mb-2 bg-dark text-white"></div>
   

    <%= yield %>

  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<head>
  
</head>
<body>
  <div class="card text-center">
      <div class="card-header">
        <h1> A propos de l'auteur</h1>
      </div>
  </div>

  <div class="alert alert-primary" role="alert">
   <h4> Nom : <%= @users.last_name %></h4>
  </div>
  <div class="alert alert-secondary" role="alert">
   <h4> Prénom : <%= @users.first_name %></h4>
  </div>
  <div class="alert alert-success" role="alert">
    <h4> Age : <%= @users.age %></h4>
  </div>
  <div class="alert alert-danger" role="alert">
    <h4> Description : <%= @users.description %></h4>
  </div>
  <div class="alert alert-warning" role="alert">
    <h4> Adresse mail : <%= @users.email %></h4>
  </div>
  <div class="alert alert-info" role="alert">
    <h4> Ville d'origine : <%= @users.city.name %></h4>
  </div>
</body>

app/views/user/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>